apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}-db-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.name }}-secretstore
    kind: SecretStore
  target:
    name: {{ .Values.name }}-db-credentials
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.postgres.secretArn }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.postgres.secretArn }}
        property: password
