apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.name }}-secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.postgres.region }}
