apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service-deployment
  labels:
    app: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart-service
        image: cartservice:local
        env:
          - name: ASPNETCORE_HTTP_PORTS
            value: "3006"
          - name: "REDIS_ADDR"
            value: "redis-service:6379"
        ports:
          - containerPort: 3006

