name: checkout-service

image:
  repository: 253260001114.dkr.ecr.ap-south-1.amazonaws.com/checkoutservice
  tag: 63d752d0fa87bec68a732b739fca1280e7c5b61b

port: 3008

env:
  - name: PORT
    value: "3008"
  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "product-catalog-service-service:3000"
  - name: CART_SERVICE_ADDR
    value: "cart-service-service:3006"
  - name: CURRENCY_SERVICE_ADDR
    value: "currency-service-service:3001"
  - name: EMAIL_SERVICE_ADDR
    value: "email-service-service:3003"
  - name: PAYMENT_SERVICE_ADDR
    value: "payment-service-service:3007"
  - name: SHIPPING_SERVICE_ADDR
    value: "shipping-service-service:3002"
