apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-service-deployment
  labels:
    app: product-catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog-service
  template:
    metadata:
      labels:
        app: product-catalog-service
    spec:
      containers:
      - name: product-catalog-service
        image: productcatalogservice:local
        env:
          - name: PORT
            value: "3000"
        ports:
          - containerPort: 3000

