image:
  tag: be9173f39bd79f2fa747ed2bbc739cc2e6192228

resources:
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
