apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad-service-deployment
  labels:
    app: ad-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad-service
  template:
    metadata:
      labels:
        app: ad-service
    spec:
      containers:
      - name: ad-service
        image: adservice:local
        env:
          - name: PORT
            value: "3004"
        ports:
          - containerPort: 3004
