apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service-deployment
  labels:
    app: shipping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
      - name: shipping-service
        image: shippingservice:local
        env:
          - name: PORT
            value: "3002"
        ports:
          - containerPort: 3002
