apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: paymentservice:local
        env:
          - name: PORT
            value: "3007"
          - name: DISABLE_PROFILER
            value: "1"
        ports:
          - containerPort: 3007
