name: cart-service

image:
  repository: 253260001114.dkr.ecr.ap-south-1.amazonaws.com/cartservice
  tag: a184cd1c062ffb1f736f178c27ed94d3cb757774

port: 3006

env:
  - name: ASPNETCORE_HTTP_PORTS
    value: "3006"
  - name: REDIS_ADDR
    value: "cache.internal.himanshu.dev:6379"
