name: loadgenerator

image:
  repository: 253260001114.dkr.ecr.ap-south-1.amazonaws.com/loadgenerator

env:
  - name: FRONTEND_ADDR
    value: "frontend-service:3009"
  - name: USERS
    value: "10"
  - name: RATE
    value: "1"
