apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-service-deployment
  labels:
    app: currency-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-service
  template:
    metadata:
      labels:
        app: currency-service
    spec:
      containers:
      - name: currency-service
        image: currencyservice:local
        env:
          - name: PORT
            value: "3001"
          - name: DISABLE_PROFILER
            value: "1"
        ports:
          - containerPort: 3001

