name: recommendation-service

image:
  repository: 253260001114.dkr.ecr.ap-south-1.amazonaws.com/recommendationservice
  tag: f7ac18f82aa3f63dddfdb584d98249a22a555516

port: 3005

env:
  - name: PORT
    value: "3005"
  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "product-catalog-service-service:3000"
