name: recommendation-service
image:
  repository: 253260001114.dkr.ecr.ap-south-1.amazonaws.com/recommendationservice
port: 3005
env:
- name: PORT
  value: "3005"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "product-catalog-service-service:3000"
