apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: currencyservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/quantinium3/aurelia.git
    targetRevision: master
    path: helm/currencyservice
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: aurelia
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
